### ISSUE TITLE
Connected the yellow (U1_TX) and green (U1_RX) cables

### ISSUE THREAD

**Issue by VINCE-HA** [RenatoDeRosa/BK7252-Ipcam-reflashing#1]
hi, kindly in the second photo you can't see how you connected the yellow (U1_TX) and green (U1_RX) cables, thanks and regards,

**Comment by RenatoDeRosa** [comment]
If you are using an Arduino you need to firstly connect EN to GND on your Arduino, then you connect gnd to GND of the cam,  tx to tx and Rx to rx

**Comment by RenatoDeRosa** [comment]
EN to GND disable the atmega on the Arduino so you can use the USB to TTL chip on the board

**Comment by VINCE-HA** [comment]
sorry I did not understand; using an Arduino you must first connect EN to GND on your Arduino, then connect gnd to GND of the cam, tx to tx and Rx to rx, this applies to (U2_TX) and (U2_RX) on the cam as per your photo; but how are the yellow (U1_TX) and green (U1_RX) cables of the cam connected, you can't see this in the second photo, I don't understand where they should be connected?
thanks

**Comment by RenatoDeRosa** [comment]
Sorry If I ask are you from India?

**Comment by VINCE-HA** [comment]
no, I'm just a newbie.
"this repository is aimed to everyone that want to approch the world of hardware hacking on small china (i'm a newby myself)"
thanks

**Comment by RenatoDeRosa** [comment]
No hate just wanted to know because I wanted to ask something to indian programmers, you can do the same, UART 1 and UART 2 are 2 different UART ,one is for reflashing the other is used as an interface to talk with the cam

**Comment by VINCE-HA** [comment]
thanks a lot and greetings,
VC

**Comment by Bluscream** [comment]
Do i have to desolder the chip to flash it?

**Comment by kumy** [comment]
@Bluscream @VINCE-HA Please send pictures of your boards

**Comment by Bluscream** [comment]
> @Bluscream @VINCE-HA Please send pictures of your boards

https://community.home-assistant.io/t/popular-a9-mini-wi-fi-camera-the-ha-challenge/230108/248?u=bluscream

https://github.com/daniel-dona/beken7252-opencam/issues/1#issuecomment-1741927676

**Comment by kumy** [comment]
We probably have the same hardware.
I did some trace tracking a long time ago, IIRC I was able to get the log console on UART2, 
I probably failed to connect on UART1 as Rx1 was so small to connect to.

I tried to flash it via SPI, but was never able to enter it in dowload mode.


![front](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/assets/176794/ce4f4a1e-5514-4435-9178-4d03a8ef0932)
![back](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/assets/176794/4399398f-431e-4800-b4ac-9a3802a458a4)

**Comment by kumy** [comment]
And another model
![front2](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/assets/176794/68b4cbc3-0e30-4d2c-bb5a-3395c23f79d5)
![back2](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/assets/176794/2510dd1f-4af1-4e57-9dff-f92b8c1e4201)

**Comment by kumy** [comment]
See page 16

[BK7252 Data Sheet.pdf](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/files/12861756/BK7252.Data.Sheet.pdf)

**Comment by VINCE-HA** [comment]
> @Bluscream @VINCE-HA Please send pictures of your boards

![1697070082710_IMG_20231007_192801](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/assets/135259414/bad005d0-60e8-4e0b-bcc4-4194406e9703)
![1697070093703_1697070091291_1697070076131_IMG_20231007_192921](https://github.com/RenatoDeRosa/BK7252-Ipcam-reflashing/assets/135259414/4e21a1fc-20cd-43b7-82af-267365308b73)

**Comment by Bluscream** [comment]
anything? please
